import {reactive} from 'vue'
import config from './config'

export const store = reactive({
    productAssortment: [
        {
            id: 0,
            nameProduct: 'Сардельки свиные',
            weight: 1000,
            cardReviews: 'Свинина, молоко, соль, перец черный, кориандр',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/1/1.png",
            productReviews: ["Тут будет описание сарделек свиных."],
            expirationDate: '10 суток',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/1/1-1.jpg", `${config.imagePath}` + "/assortment/1/1-2.jpg"],
            typeProduction: 'sosiski',
            actionPrice: false,
        },
        {
            id: 1,
            nameProduct: 'Сосиски молочные',
            weight: 1000,
            cardReviews: 'Свинина, говядина, молоко, яйцо, соль, специи',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/1/1.png",
            productReviews: ["Тут будет описание сосисок молочных."],
            expirationDate: '10 суток',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/1/1-1.jpg", `${config.imagePath}` + "/assortment/1/1-2.jpg"],
            typeProduction: 'sosiski',
            actionPrice: true,
        },
        {
            id: 2,
            nameProduct: 'Сосиски куриные. Диетический продукт',
            weight: 1000,
            cardReviews: 'Филе грудки, филе бедра курицы, соль, специи',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/1/1.png",
            productReviews: ["Тут будет описание сосисок куриных."],
            expirationDate: '10 суток',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/1/1-1.jpg", `${config.imagePath}` + "/assortment/1/1-2.jpg"],
            typeProduction: 'sosiski',
            actionPrice: false,
        },
        {
            id: 3,
            nameProduct: 'Ветчина из свинины',
            weight: 1000,
            cardReviews: 'Лопатка свиная, соль, смесь пряностей',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/2/2.jpg",
            productReviews: ["Тут будет описание ветчины свиной."],
            expirationDate: '10 суток',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/2/2-1.jpg", `${config.imagePath}` + "/assortment/2/2-2.jpg",],
            typeProduction: 'sausages',
            actionPrice: true,
        },
        {
            id: 4,
            nameProduct: 'Ветчина из индейки прессованая',
            weight: 1000,
            cardReviews: 'Филе бедра индейки, соль, сахар, черный перец',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/3/3.jpg",
            productReviews: ["Непеченая ветчина из мяса индейки."],
            expirationDate: '10 суток',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/3/3-1.jpg", `${config.imagePath}` + "/assortment/3/3-2.jpg",],
            typeProduction: 'sausages',
            actionPrice: false,
        },   
    ],
})