import {reactive} from 'vue'
import config from './config'

export const store = reactive({
    productAssortment: [
        {
            id: 0,
            nameProduct: 'Сардельки свиные',
            weight: 1000,
            cardReviews: 'Свинина, молоко, соль нитритная, перец черный, кориандр',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/1/1.png",
            productReviews: ["Свиные сардельки в натуральной оболочке. Сочные, ароматные с легким копчением."],
            expirationDate: '10 суток.',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С.',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/1/1-1.jpg", `${config.imagePath}` + "/assortment/1/1-2.jpg"],
            typeProduction: 'sosiski',
            actionPrice: false,
        },
        {
            id: 1,
            nameProduct: 'Сосиски молочные',
            weight: 1000,
            cardReviews: 'Свинина, говядина, молоко, яйцо, соль нитритная, специи.',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/plug.png",
            productReviews: ["Тут будет описание сосисок молочных."],
            expirationDate: '10 суток.',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С.',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/plug-big.png"],
            typeProduction: 'sosiski',
            actionPrice: true,
        },
        {
            id: 2,
            nameProduct: 'Сосиски куриные',
            weight: 1000,
            cardReviews: 'Филе грудки, филе бедра курицы, соль нитритная, специи.',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/plug.png",
            productReviews: ["Диетический продукт."],
            expirationDate: '10 суток.',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С.',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/plug-big.png"],
            typeProduction: 'sosiski',
            actionPrice: false,
        },
        {
            id: 3,
            nameProduct: 'Ветчина из свинины',
            weight: 1000,
            cardReviews: 'Лопатка свиная, соль нитритная, смесь пряностей.',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/3/3.jpg",
            productReviews: ["Тут будет описание ветчины свиной."],
            expirationDate: '10 суток.',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С.',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/3/3-1.jpg", `${config.imagePath}` + "/assortment/3/3-2.jpg",],
            typeProduction: 'sausages',
            actionPrice: true,
        },
        {
            id: 4,
            nameProduct: 'Ветчина из индейки прессованая',
            weight: 1000,
            cardReviews: 'Филе бедра индейки, соль нитритная, сахар, черный перец.',
            cardPrice: 500,
            cardImage: `${config.imagePath}` + "/assortment/2/2.jpg",
            productReviews: ["Нежная ветчина из мяса индейки."],
            expirationDate: '10 суток.',
            storageСonditions: 'Хранить при температуре от 2.0 °С до 6.0 °С.',
            modalState: false,
            reviewsPhotosProduct: [`${config.imagePath}` + "/assortment/2/2-1.jpg", `${config.imagePath}` + "/assortment/2/2-2.jpg",],
            typeProduction: 'sausages',
            actionPrice: false,
        },   
    ],
})